# Generated by Django 5.0.4 on 2024-04-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('t_sana', models.DateField(blank=True)),
                ('davlat', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('janr', models.CharField(max_length=200)),
                ('yil', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('davomiyligi', models.CharField(max_length=10)),
                ('narx', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KinoActer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmApp.acter')),
                ('kino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmApp.kino')),
            ],
        ),
    ]
